# Numpy Examples

Adapted from the [Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html)

## An Example

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape  # the dimensions of the array. This is a tuple of integers indicating the size of the array in 
         # each dimension. For a matrix with n rows and m columns, shape will be (n,m). 
         # The length of the shape tuple is therefore the number of axes, ndim.

(3, 5)

In [6]:
a.ndim  # the number of axes (dimensions) of the array.

2

In [7]:
a.size  # the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [8]:
a.dtype.name  # an object describing the type of the elements in the array. 
              # One can create or specify dtype’s using standard Python types. 
              # Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are
              # some examples.

'int64'

In [6]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])

In [10]:
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray


## Array Creation

In [3]:
a = np.array([2,3,4])

In [4]:
a

array([2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [6]:
b = np.array([1.2, 3.5, 5.1])

In [7]:
b.dtype

dtype('float64')

In [8]:
a = np.array(1,2,3,4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [9]:
# 'array' transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into 
# three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])

In [10]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [12]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

The function 'zeros' creates an array full of zeros, the function 'ones' creates an array full of ones, and the 
function 'empty' creates an array whose initial content is random and depends on the state of the memory. 

By default, the dtype of the created array is float64.

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
np.empty( (2,3) )                                 # uninitialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [16]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [17]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When *arange* is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function *linspace* that receives as an argument the number of elements that we want, instead of the step.

In [19]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

## Printing Arrays